# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       xorg-x11-xauth
Summary:    X.Org X11 X authority utilities
Version:    1.0.4
Release:    1
Group:      System/X11
License:    MIT/X11
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/app/xauth-%{version}.tar.bz2
Source1:    mkxauth
Source2:    mkxauth.man
Source100:  xorg-x11-xauth.yaml
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xau)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xmuu)
Provides:   xauth mkxauth


%description
Description: %{summary}



%prep
%setup -q -n xauth-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install 
mkdir -p %{buildroot}%{_bindir}/
cp -a %{SOURCE1} %{buildroot}%{_bindir}/
mkdir -p %{buildroot}%{_mandir}/man1/
cp -a %{SOURCE2} %{buildroot}%{_mandir}/man1/


# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING NEWS README ChangeLog
%{_bindir}/xauth
%{_bindir}/mkxauth
%doc %{_mandir}/man1/xauth.1*
%doc %{_mandir}/man1/mkxauth.man*
# << files


